version : "3.7"

services : 

  server : 
    build :
      context : .
      dockerfile : Dockerfile

    command : ["go" , "run" , "."]

    ports:
      - "8080:8080"

  redis :
    image : "redis"    
    ports:
      - "6379:6379"