name: golang-pipeline
on: 
  push:
    barnches :
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests        
        - run : docker pull redis
        - run : docker run --name redis-test-instance -p 6379:6379 -d redis
        - run : go test ./...